ktor {
	deployment {
		port = 8413
	}
	application {
		modules = [ uk.me.cormack.lighting7.ApplicationKt.module ]
	}
}

anthropic {
	apiKey = ${?ANTHROPIC_API_KEY}
	model = "claude-sonnet-4-20250514"
}
