plugins {
    kotlin("jvm")
    application
    id("com.gradleup.shadow")
}

kotlin {
    jvmToolchain(24)
}

repositories {
    mavenCentral()
}

application {
    mainClass.set("uk.me.cormack.lighting7.launcher.LauncherMainKt")
}

dependencies {
    // Pure JDK only — `java.awt.SystemTray`, `java.net.http`, `java.awt.Desktop` cover
    // every responsibility (process spawning, readiness polling, browser open, tray menu).
    // Keeping this lean matters for jpackage in Phase 3: every extra dep grows the
    // installer.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}

// Single-shot dev run: build the backend + compiler-server fat jars in the root project
// and pass their absolute paths to the launcher via system properties. Without these,
// LauncherMain falls back to looking for siblings of its own JAR (the jpackage layout).
tasks.named<JavaExec>("run") {
    dependsOn(":shadowJar", ":assembleCompilerServer")
    // Property name = JAR filename, so LauncherMain's resolveJar() can look up either
    // child by passing the bare filename through `System.getProperty`.
    systemProperty("lighting7.jar", rootProject.layout.buildDirectory.file("libs/lighting7.jar").get().asFile.absolutePath)
    systemProperty("kotlin-compiler-server.jar", rootProject.layout.buildDirectory.file("distributions/kotlin-compiler-server.jar").get().asFile.absolutePath)
}

// Phase 3 packaging: jpackage's --input wants exactly one launcher.jar. The shadow
// plugin merges kotlin-stdlib (the only non-JDK dep) into a single self-contained
// jar so the install layout stays to three flat jars. mergeServiceFiles() mirrors
// the root shadowJar config — kept in sync if launcher ever picks up SPI deps.
// This subproject declares no `version`, so the plain `jar` task's default output name is
// also `launcher.jar` — the same path shadowJar writes. Whichever task ran last won, so
// `stageJpackageInput` could stage the *thin* jar (no kotlin-stdlib, no Main-Class) and
// produce an installer whose tray launcher dies with NoClassDefFoundError on Intrinsics.
// Give the thin jar a classifier so only shadowJar owns `launcher.jar`.
tasks.jar {
    archiveClassifier.set("thin")
}

tasks.shadowJar {
    archiveFileName.set("launcher.jar")
    // See the root build's shadowJar for why INCLUDE is needed and why preserve-first is
    // paired with it. This module only bundles kotlin-stdlib, so there is nothing to
    // preserve-first today — mergeServiceFiles() is kept in sync with the root config in
    // case launcher ever picks up SPI deps, and failOnDuplicateEntries will flag it if so.
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    failOnDuplicateEntries.set(true)
    mergeServiceFiles()
}

// LauncherMain.ensureDefaultConfig() reads `/default-local.conf` from the launcher
// classpath on first install. Generate it from the canonical example.local.conf
// at the repo root so the two files can't drift.
val stageDefaultConfig = tasks.register<Copy>("stageDefaultConfig") {
    from(rootProject.file("example.local.conf"))
    into(layout.buildDirectory.dir("generated/resources/default-config"))
    rename { "default-local.conf" }
}

// LauncherMain passes six `--libraries.folder.*` flags naming `<kotlinVersion>[-js|-wasm|…]/`
// directories that assembleCompilerServer stages next to the compiler-server jar. Both sides have
// to agree on that version, so it is written into a resource here from the single
// `compilerServerKotlinVersion` property rather than hardcoded in Kotlin — hand-syncing six string
// literals against a Gradle property is exactly how the script editor broke on the last Kotlin bump.
val compilerServerKotlinVersion: String =
    (rootProject.findProperty("compilerServerKotlinVersion") as String?)?.takeIf { it.isNotBlank() }
        ?: error("compilerServerKotlinVersion is not set or is blank — declare it in gradle.properties.")

val stageCompilerServerVersion = tasks.register("stageCompilerServerVersion") {
    val outputDir = layout.buildDirectory.dir("generated/resources/compiler-server")
    inputs.property("compilerServerKotlinVersion", compilerServerKotlinVersion)
    outputs.dir(outputDir)
    doLast {
        val dir = outputDir.get().asFile.apply { mkdirs() }
        dir.resolve("compiler-server.properties").writeText(
            "# Generated by :launcher:stageCompilerServerVersion — do not edit.\n" +
                "kotlinVersion=$compilerServerKotlinVersion\n"
        )
    }
}

sourceSets.main {
    resources.srcDir(stageDefaultConfig)
    resources.srcDir(stageCompilerServerVersion)
    // Consume the ROOT project's generateBuildInfo output rather than regenerating it here.
    // The launcher and the backend are separate jars inside one installer and MUST agree on the
    // version byte-for-byte — a mismatch would surface as the app reporting one version while
    // the updater compares another, i.e. an update that reinstalls itself forever.
    //
    // Regenerating it locally (the stageCompilerServerVersion shape above) would make the Gradle
    // *property* the source of truth and fork the derivation logic — the defaulting, the MSI
    // version validation, the channel check — into two build files. One task, two consumers.
    //
    // This is a dependency on a task's output *file*, not on the root project's classpath.
    // Nothing new lands on the launcher's compile or runtime classpath, so the pure-JDK
    // invariant this module is built around is untouched.
    resources.srcDir(rootProject.tasks.named("generateBuildInfo"))
}
