package uk.me.cormack.lighting7.update

import org.slf4j.LoggerFactory
import java.time.Instant
import java.util.Properties

private val logger = LoggerFactory.getLogger("BuildInfo")

/** Marker used to resolve the resource off this jar's classpath. */
private object BuildInfoMarker

/**
 * What this build *is* — read from `/lighting7-build-info.properties`, generated by
 * `:generateBuildInfo` and staged into both `lighting7.jar` and `launcher.jar` from that one
 * task, so the two can never disagree about the version.
 *
 * Deliberately does **not** carry "is this a packaged install". The packaging pipeline stages the
 * exact same `lighting7.jar` that `./gradlew run` executes, so packaged-ness is not knowable at
 * build time. The launcher detects it at runtime and forwards it in the environment — see
 * [InstallKind].
 */
data class BuildInfo(
    val version: String,
    val channel: Channel,
    val commitSha: String?,
    val commitTimestamp: Instant?,
) {
    enum class Channel {
        /** Built by the release workflow, from a `v*` tag. The only channel that may self-update. */
        RELEASE,

        /** Anything else: a local `./gradlew run`, or a hand-built installer. */
        DEV,
    }

    val shortSha: String? get() = commitSha?.take(7)

    companion object {
        /** Version reported when the resource is missing entirely (IDE runs, tests). */
        internal const val UNKNOWN_VERSION = "0.0.0"

        val current: BuildInfo by lazy { load() }

        private val unknown = BuildInfo(UNKNOWN_VERSION, Channel.DEV, null, null)

        internal fun load(): BuildInfo {
            // Never throws. A missing or malformed resource means "we don't know what we are",
            // which correctly disables self-update — and must not take down a lighting desk.
            val stream = BuildInfoMarker::class.java.getResourceAsStream("/lighting7-build-info.properties")
            if (stream == null) {
                // Expected when running from a classes directory without processResources.
                logger.debug("No /lighting7-build-info.properties on the classpath; reporting an unknown dev build.")
                return unknown
            }

            val props = try {
                Properties().also { p -> stream.use { p.load(it) } }
            } catch (e: Exception) {
                logger.warn("Could not read /lighting7-build-info.properties; reporting an unknown dev build.", e)
                return unknown
            }

            return parse(props)
        }

        /** Split from [load] so the fail-closed rules below are testable without a classpath fixture. */
        internal fun parse(props: Properties): BuildInfo = BuildInfo(
            version = props.getProperty("version")?.takeIf { it.isNotBlank() } ?: UNKNOWN_VERSION,
            // Anything that is not literally "release" is DEV. Failing closed matters here: a
            // typo in the generated property must not enable the self-update path.
            channel = if (props.getProperty("channel") == "release") Channel.RELEASE else Channel.DEV,
            commitSha = props.getProperty("commitSha")?.takeIf { it.isNotBlank() },
            // An unparseable timestamp degrades to null rather than throwing — it is display
            // metadata, and nothing about updating depends on it.
            commitTimestamp = props.getProperty("commitTimestamp")
                ?.takeIf { it.isNotBlank() }
                ?.let { raw -> runCatching { Instant.parse(raw) }.getOrNull() },
        )
    }
}

/**
 * How this process was started, as reported by the launcher over the environment. The backend
 * cannot work this out for itself — it is a plain `java -jar` child either way.
 */
enum class InstallKind {
    /** Launched from a jpackage installer. The only kind that can be updated in place. */
    PACKAGED,

    /** `./gradlew run`, a bare `java -jar`, or tests. */
    DEV,

    ;

    companion object {
        const val ENV_VAR = "LIGHTING7_INSTALL_KIND"

        fun fromEnv(env: (String) -> String? = System::getenv): InstallKind =
            if (env(ENV_VAR) == "packaged") PACKAGED else DEV
    }
}
