package uk.me.cormack.lighting7.launcher

import java.nio.file.Files
import java.nio.file.Path
import java.util.Properties

/**
 * The launcher's half of the build identity. Reads the same
 * `/lighting7-build-info.properties` the backend does — one file, generated by the root
 * project's `:generateBuildInfo` and staged into both jars, so the two can never disagree
 * about what version is installed.
 *
 * This never `error()`s. It runs on the path that keeps the tray icon alive, so the same
 * "don't take the whole app down mid-show" reasoning documented in `LauncherMain.main` applies:
 * unknown-version simply means self-update is off. (It used to be contrasted here with
 * `compilerServerKotlinVersion`, which *could* fail loudly because losing the script editor was
 * survivable — that function went with the bundled compiler server.)
 */
internal object LauncherBuildInfo {
    private val props: Properties by lazy {
        val loaded = Properties()
        runCatching {
            LauncherMarker::class.java.getResourceAsStream("/lighting7-build-info.properties")
                ?.use { loaded.load(it) }
        }.onFailure { println("WARNING: could not read /lighting7-build-info.properties (${it.message}).") }
        loaded
    }

    val version: String get() = props.getProperty("version")?.takeIf { it.isNotBlank() } ?: "0.0.0"

    /** True only for builds produced by the release workflow. Anything else fails closed to dev. */
    val isRelease: Boolean get() = props.getProperty("channel") == "release"
}

/**
 * Whether this process is running from a jpackage installer or from a development checkout.
 *
 * This cannot be a build-time fact: `stageJpackageInput` packages the very same `launcher.jar`
 * and `lighting7.jar` that `:launcher:run` executes, so there is no build in which the jars
 * themselves differ. Only the *layout around them* at runtime distinguishes the two.
 *
 * Two independent signals, because either alone is a single point of failure:
 *  - `jpackage.app-path`, set by jpackage's native launcher (JDK 18+). Cheap, but a property
 *    the JDK could stop setting.
 *  - `.jpackage.xml`, which jpackage writes into the app image next to the jars. Layout-derived,
 *    so it survives a JDK change.
 */
internal fun detectInstallKind(launcherJarDir: Path?): String {
    val hasAppPath = !System.getProperty("jpackage.app-path").isNullOrBlank()
    val hasAppImageMarker = launcherJarDir?.let { Files.exists(it.resolve(".jpackage.xml")) } == true
    return if (hasAppPath || hasAppImageMarker) "packaged" else "dev"
}

/**
 * The root of a jpackage installation — the directory holding `lighting7.exe`, given a
 * `launcher.jar` that lives in `<root>/app/`. Null when not running from an installer.
 *
 * Derived from the launcher jar's own location rather than from `jpackage.app-path` because we
 * are demonstrably running from it, which makes it the more reliable of the two. `--win-dir-chooser`
 * means the user picks this directory at install time, and an MSI major upgrade reuses the
 * recorded INSTALLDIR, so it stays valid across updates.
 */
internal fun installRoot(launcherJarDir: Path?): Path? {
    if (launcherJarDir == null) return null
    if (!Files.exists(launcherJarDir.resolve(".jpackage.xml"))) return null
    return launcherJarDir.parent
}
